### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by prabhu8511** [TarikHuber/material-ui-responsive-drawer#11]
Getting below error: 
./node_modules/material-ui-responsive-drawer/es/ResponsiveAppBar.js
Module not found: Can't resolve 'material-ui/AppBar'

yarn add @material-ui/core also didn't work 

Please help me with this 

Thanx in advance

**Comment by TarikHuber** [comment]
Hi @prabhu8511 this project is deprecated and no longer supported. Material-UI has some own demos for a responsive menu and there is also open source code for the new version integrated here: https://github.com/TarikHuber/react-most-wanted
