### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by thm-design** [TarikHuber/material-ui-responsive-drawer#4]
Hey @TarikHuber nice job with these files, I just started looking into MUI and your repo has been very helpful to get a layout set to experiment and learn.

I have a branch I would like to PR that fixes some spelling typos for material-ui-responsive-drawer  if you are interested, just need collab permissions.

**Comment by TarikHuber** [comment]
Hi @thm-design , thx :) you have here also a complete example of a MUI project: [React Most Wanted](https://github.com/TarikHuber/react-most-wanted)

PR-s are always welcome. You can fork the project and send PR with your changes to this one. I'll check them immediately and update the npm package.

**Comment by thm-design** [comment]
PR'd in https://github.com/TarikHuber/material-ui-responsive-drawer/pull/5
