### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jwchang0206** [TarikHuber/material-ui-responsive-drawer#6]
nvm

**Comment by TarikHuber** [comment]
Hi. I thing you found the soulution. Just set the initial state into index.js file of state folder. That can also be used to setup the default theme and intl. I will write it into the docs 😄

**Comment by jwchang0206** [comment]
do you think
`<ResponsiveDrawer open={false}>` and set it true later will help?

**Comment by TarikHuber** [comment]
No. Don't do that. You weould need to take care of the open state and this project is made to avoid that. Find the place where you initialise the state for your redux app and set in the initial state

```json

initialState={
responsiveDrawer: {
open: false
}
}

```

Check it out [here](https://github.com/TarikHuber/react-most-wanted). Thats a complete intergration example. Go there to the config file and add to initial config the part abowe with the `responsiveDrawer` part.
