### ISSUE TITLE
BodyContainer with nested Route issue

### ISSUE THREAD

**Issue by mindtricksdev** [TarikHuber/material-ui-responsive-drawer#7]
Hello,
I like your responsive drawer idea!

I am experiencing some issues with nested `<Route>` (react-router v4) elements inside the `<BodyContainer>`. I was expecting that the routing will still work. However, the `render` does not trigger after a route change.

I was able to change the `<BodyContainer>` to a simple `<div>` to make it work but now I need to handle the widths manually. Is there any plan for this to be supported?

Thanks

**Comment by TarikHuber** [comment]
Hi,

Have you tried to put the BodyContainer inside the Route?
Take a look into [this](https://github.com/TarikHuber/react-most-wanted) demo project that demonstrates the usage of this and other libraries.

**Comment by mindtricksdev** [comment]
The demo project looks great.
This does indeed fix my issue.

Thanks!
