### ISSUE TITLE
Suddenly sandwich icon appears on right

### ISSUE THREAD

**Issue by sandorvasas** [TarikHuber/material-ui-responsive-drawer#8]
Hi,

An issue of the sandwich icon appeared for me. I checked applied css styles and tried to enable-disable each of them without luck. I'm not sure why this is happening. See the screenshots below.

<img width="754" alt="sandwich-1" src="https://user-images.githubusercontent.com/9200077/28168542-b681a38a-67df-11e7-88ea-0e628127a35e.png">
<img width="358" alt="sandwich-2" src="https://user-images.githubusercontent.com/9200077/28168547-b9563378-67df-11e7-9313-a1771c024077.png">

Is this kind of a known issue or do you have any clues how to fix it besides applying additional css -- would be too hackish?

Thanks,
Sandor

**Comment by TarikHuber** [comment]
Hi @sandorvasas ,

Are you using the stable or next version?
Do you have some of you'r code I could check?

You can find in this repo [react-most-wanted](https://github.com/TarikHuber/react-most-wanted) a complete example how to use this project.

**Comment by sandorvasas** [comment]
I'm using the stable version.
Don't have code, which is the origin of the problem since I don't know where any related changes were introduced that could affect the sandwich icon. Before that specific unknown change it had been working fine.

I keep investigating further and share any results.

**Comment by sandorvasas** [comment]
So far I believe there is an incompatibility with material-ui-icons package. Whenever I install it, the gray div appears on the right.

**Comment by TarikHuber** [comment]
Do you have a small code snipped on how you use this module?

**Comment by sandorvasas** [comment]
<img width="950" alt="material-ui-responsive-drawer-codesnippet" src="https://user-images.githubusercontent.com/9200077/28173397-a50646ec-67ee-11e7-858e-3bc092fe9da6.png">

There is nothing special. I had used this module before in another project and it worked fantastic. I feel this happens because of upgrading probably the drawer package itself and installing material-ui-icons, but not sure about it more precisely. It's not my css surely, since I tried also without *any* css.

**Comment by TarikHuber** [comment]
Have you tried to remove all those child components from `ResponsiveDrawer`?

**Comment by sandorvasas** [comment]
It seems this issue is present in version 1.2.3. Installing 1.1.31 resolved it. 

Thanks

**Comment by TarikHuber** [comment]
Yes that could cause the problem because the version 1.2.x is prepared for the material-ui@next
