### ISSUE TITLE
Unknown prop `onLeftIconButtonClick` 

### ISSUE THREAD

**Issue by sarincasm** [TarikHuber/material-ui-responsive-drawer#9]
I see this warning message on the console when I include the `ResponsiveAppBar` - 

Warning: Unknown prop `onLeftIconButtonClick` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

```
return <ResponsiveAppBar
			title={title}
			iconElementRight={elementRight}
		/>

```

I am using version 1.19.4

**Comment by TarikHuber** [comment]
Hi @eelsweb,

What material-ui version are you using? They changed from using tab to click. If you are on a older version this kind of error message would be displayed.

Can you please check that.

**Comment by sarincasm** [comment]
ofcourse :)
thanks for looking into this quickly.. updating material-ui got rid of the warning
